[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/_ipx/:quality/:width/:url"
  to = "/.netlify/images"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}
